---
# defaults file for orange.hr.getvault
# variable prefix is : 
debug: false
VaultToken: "{{ lookup('ansible.builtin.file', '~/.vault-token', errors='ignore')| from_yaml | default('NA',true) }}"
Path: dev/devices/asr1-nanterre
EngineMountPoint: app
AuthMethod: token
VaultAddr: "https://area51-montsouris.hbx.geo.francetelecom.fr"
NameSpace : AIAC/HR
Register: secret
CaCert: /etc/ssl/certs/orange-certificates.crt
