---
# tasks file for orange.hr.vault


# GET VAULT CREDENTIALS
- name: BLOCK GET CREDENTIALS
  block:
    - name: "DEBUG : PATH"
      ansible.builtin.debug:
        msg:
          - "path : {{ Path }}"
      
    - name: "DEBUG : VAR FOR VAULT GET CREDENTIALS"
      ansible.builtin.debug:
        msg:
          - "vault token : {{ VaultToken }}"
          - "path : {{ Path }}"
          - "engine_mount_point : {{ EngineMountPoint }}"
          - "auth_method : {{ AuthMethod }}"
          - "url : {{ VaultAddr }}"
          - "CACert : {{ CaCert }}"
      when: debug or DEBUG

    - name: GET CREDENTIALS
      community.hashi_vault.vault_kv2_get:
        # path: dev/devices/asr1-nanterre
        path: "{{ Path }}"
        # engine_mount_point: app
        engine_mount_point: "{{ EngineMountPoint }}"
        # auth_method: token
        auth_method: "{{ AuthMethod }}"
        # token: "{{ vault_token }}"
        token: "{{ VaultToken }}"
        # url: "{{ vault_addr }}"
        url: "{{ VaultAddr }}"
        # namespace: AIAC/HR
        namespace: "{{ NameSpace }}"
        # cacert: /etc/ssl/certs/orange-certificates.crt
        cacert: "{{ CaCert }}"
        # kv_version: 2
      register: Secret

    - name: "DEBUG : GET CREDENTIALS -> SECRETS "
      ansible.builtin.debug:
        msg:
          - "Secrets récupérés : {{ Secret }}"
      when: debug or DEBUG

  rescue: 
    - name: "GET CREDENTIALS ISSUE"
      vars:
        - failed: true
      ansible.builtin.debug:
        msg:
          - "⚠️  Erreur de connexion à VAULT"
          - "-> merci de vérifier que le token de connexion à vault n'a pas expiré"
      failed_when: failed
  # tags: get
  when: 
    - ohrvaultGet is defined
    - ohrvaultGet

# SET CREDENTIALS FACTS
- name: BLOCK SET CREDENTIALS FACTS
  block:
    - name: Set credentials facts for host
      set_fact:
        "{{ item.name }}" : "{{ item.path }}"
      with_items: "{{ credentials }}"

    - name: DEBUG credentials facts for host
      ansible.builtin.debug:
        msg: "{{ item.name }} : {{ item.path }}"
      with_items: "{{ credentials }}"
      when: debug or DEBUG

    - name: DEBUG VARS
      ansible.builtin.debug:
        msg:
          - "login : {{ username }}"
          - "password : {{ password }}"
          - "created_time : {{ created_time }}"
      when: debug or DEBUG
  # tags: set
  when : 
    - ohrvaultSet is defined
    - ohrvaultSet


# - name: DEBUG VARS
#   ansible.builtin.debug:
#     msg:
#       # - "ansible user : {{ ansible_user }}"
#       # - "ansible pwd : {{ ansible_password }}"
#       - "vault secret : {{ secret.data | to_nice_json }}"